
version: '3.7'

services:
  webapi:
    build:
        context: ./finance-web-api
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  reports-service:
    build:
        context: ./finance-reports-service
        dockerfile: Dockerfile
    ports:
        - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  mail-service:
    build:
        context: ./finance-mail-service
        dockerfile: Dockerfile
    ports:
        - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=finance
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres