spring:
  application:
    name: BUDGET-APP
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  docker:
    compose:
      enabled: false
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP

server:
  port: 8081

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/