spring:
  application:
    name: REPORTS-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    exchange: reports-exchange
    routing:
      key:
        weekly: reports.weekly
        monthly: reports.monthly
        custom: reports.custom
    queue: reports-queue
jwt:
    secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
server:
  port: 8083
  address: 0.0.0.0



reports:
  folder:
    root: ../reports

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
