version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
        - app-network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
        - app-network

  webapi:
    build:
      context: ../budget-app
      dockerfile: ../budget-app/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
        - app-network

  reports-service:
    build:
      context: ../reports-service
      dockerfile: ../reports-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
      - webapi
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING.RABBITMQ.HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - app-network

  mail-service:
    build:
      context: ../mail-app
      dockerfile: ../mail-app/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING.RABBITMQ.HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
        - app-network


  eureka-server:
    build:
      context: ../budget-service-registry
      dockerfile: ../budget-service-registry/Dockerfile
    ports:
        - "8761:8761"
    networks:
        - app-network

  cloud-gateway:
    build:
      context: ../budget-api-gateway
      dockerfile: ../budget-api-gateway/Dockerfile
    ports:
        - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
        - eureka-server
    networks:
        - app-network

  authentication-service:
    build:
      context: ../authentication-service
      dockerfile: ../authentication-service/Dockerfile
    ports:
      - "9898:9898"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
