package pl.sonmiike.reportsservice.report.types;

public enum ReportDataKey {
    USER,
    DATE_INTERVAL,
    TOTAL_EXPENSES,
    LARGEST_EXPENSE,
    AVERAGE_WEEKLY_EXPENSE,
    WEEK_WITH_HIGHEST_EXPENSES,
    DAY_WITH_HIGHEST_AVERAGE_EXPENSE,
    TOTAL_INCOMES,
    BUDGET_SUMMARY,
    EXPENSES_LIST,
    INCOME_LIST,
    CATEGORY_EXPENSES,

    BIGGEST_EXPENSE,
    SMALLEST_EXPENSE,
    AVERAGE_DAILY_EXPENSE,
}
