spring:
  cloud:
    gateway:
      routes:
        - id: budget-app
          uri: lb://BUDGET-APP
          predicates:
            - Path=/me/**
          filters:
            - AuthenticationFilter

        - id: reports-service
          uri: lb://REPORTS-SERVICE
          predicates:
            - Path=/report/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: BUDGET-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
